### ISSUE TITLE
Multiple remotes are broken

### ISSUE THREAD

**Issue by Commandcracker** [unicornpkg/libunicornpkg#19]
![Screenshot_20221107_154245](https://user-images.githubusercontent.com/49335821/200338568-b0e63c1a-6893-4458-9483-d200cb7f0ed0.png)

**Comment by tomodachi94** [comment]
I've applied [a band-aid in Wing](https://github.com/unicornpkg/wing/commit/24716d04a0b231c81c15f66ad0f806aeea83b3bf) to fix the problem, but things are still very much broken. I am not sure what bit of logic is causing this.
