### ISSUE TITLE
Integrity and hashing support

### ISSUE THREAD

**Issue by tomodachi94** [unicornpkg/libunicornpkg#2]
Calculate a hash of the file on package generation, and verify it on installation.

See also: #1

**Comment by tomodachi94** [comment]
See [documentation](https://unicornpkg.madefor.cc/specification/package-tables.html#security)

**Comment by tomodachi94** [comment]
This would likely introduce a new dependency, [Anavrins' `sha256` library](http://www.computercraft.info/forums2/index.php?/topic/8169-).

**Comment by SkyTheCodeMaster** [comment]
You should not use that library, instead use this one: [Anavrin's `sha256` library.](https://pastebin.com/6UV4qfNF)

**Comment by Commandcracker** [comment]
You might be interested in my custom version of Anavrin's fun, where i separated the ByteArray class and made it a bit moor "refined".
[bytearray.lua](https://github.com/Commandcracker/oculusos3.0/blob/main/src/lib/bytearray.lua)
[sha256.lua](https://github.com/Commandcracker/oculusos3.0/blob/main/src/lib/sha256.lua)
_(Oculus OS is discontinued, I might make another OS tats based around unicornpkg)_
