### ISSUE TITLE
Wrong implementation of org.bitbucket

### ISSUE THREAD

**Issue by Commandcracker** [unicornpkg/libunicornpkg#35]
This is how a bitbucket raw URL works:
`https://bitbucket.org/<owner>/<name>/raw/<reference>/<file>`

https://github.com/unicornpkg/libunicornpkg/blob/7772a0cf8393cdcfe5f26b9c511f9e2f382f66f3/unicorn/provider/org.bitbucket.lua#L7-L14

**Comment by tomodachi94** [comment]
I'll fix this in a bit.
