### ISSUE TITLE
`script` support lacking nil check

### ISSUE THREAD

**Issue by fatboychummy** [unicornpkg/libunicornpkg#39]
**Describe the bug**
When attempting to run `/bin/hoof install unix-path-bootstrap`, a nil value error is generated. I've traced it back to the file located at https://unicornpkg.github.io/unicornpkg-main/unix-path-bootstrap.lua -- there is no `.script` field in the package information.

**To Reproduce**
1. With a completely new system, run `wget run https://unicornpkg.github.io/wing/install.lua`
2. Run the bootstrap installation `/bin/hoof install unix-path-bootstrap`
3. See error

**Expected behavior**
Bootstrap to occur without error

**Screenshots**
![image](https://user-images.githubusercontent.com/39929480/208284275-c545748f-e78d-4b1b-b63a-7e6179e36b69.png)

**Environment (please complete the following information):**
- Emulator or mod (including version): CraftOS-PC (1.101.1 on v2.7.2)
- OS:Windows 10
- ROM version: 1.101.1?
- Program hash or version: Not exactly sure where to get this information

**Additional context**
None

**Comment by tomodachi94** [comment]
This isn't a bug in a package, this is a bug in the `script` module. https://github.com/unicornpkg/libunicornpkg/blob/main/unicorn/core.lua#L119

**Comment by tomodachi94** [comment]
I'm going to do a quick release to make sure this fix gets out ASAP.

**Comment by tomodachi94** [comment]
Release is out, thanks for reporting!
